In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd
import numpy as np
# Set the display option to use scientific notation
pd.set_option('display.float_format', '{:.2e}'.format)
pd.set_option('display.max_rows', 30)

In [2]:
#Write name of location of the folder 
path_directory="your path to the folder containing the code and data folders"

In [3]:
# Import CF shapefile -- The shapefile contains country geometry of GLAM (ISO3CD, ROMNAM)

CF=gpd.read_file(path_directory+'/results/CF/CF.shp', driver='ESRI Shapefile') #projection: WGS 84

#change name to clarify : CF reg is just calculated using regional EF, but subriver basin FF
CF=CF.rename(columns={"CF_regiona":"CF_EF_reg"})

#calculate area per subriver basin
CF["cell_area"]=CF.area
CF

<ipython-input-3-afa6dd27ed46>:9: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  CF["cell_area"]=CF.area

,BAS34S_ID,Scarcity,TOTAL_avai,dom,ISO3CD,ROMNAM,XF,EF,Region (Wo,Region (Un,Region (WB,Region,Sub-region,Mean EF re,CF,CF_EF_reg,geometry,cell_area
0,2,0.00e+00,7.68e+06,0.00e+00,DNK,Denmark,0.00e+00,8.41e-05,Europe and Central Asia,Europe and Northern America,Europe and Central Asia,Europe,Northern Europe,1.12e-04,0.00e+00,0.00e+00,"POLYGON ((-37.88129 83.49997, -37.86035 83.500...",2.06e-03
1,4,0.00e+00,1.49e+07,0.00e+00,DNK,Denmark,0.00e+00,8.41e-05,Europe and Central Asia,Europe and Northern America,Europe and Central Asia,Europe,Northern Europe,1.12e-04,0.00e+00,0.00e+00,"MULTIPOLYGON (((-36.79602 83.49997, -36.79509 ...",1.82e-02
2,5,0.00e+00,1.60e+07,0.00e+00,DNK,Denmark,0.00e+00,8.41e-05,Europe and Central Asia,Europe and Northern America,Europe and Central Asia,Europe,Northern Europe,1.12e-04,0.00e+00,0.00e+00,"POLYGON ((-36.50003 83.49997, -36.50003 83.562...",3.09e-02
3,6,0.00e+00,1.63e+07,0.00e+00,DNK,Denmark,0.00e+00,8.41e-05,Europe and Central Asia,Europe and Northern America,Europe and Central Asia,Europe,Northern Europe,1.12e-04,0.00e+00,0.00e+00,"POLYGON ((-36.00003 83.49997, -36.00003 83.558...",2.79e-02
4,7,0.00e+00,1.59e+07,0.00e+00,DNK,Denmark,0.00e+00,8.41e-05,Europe and Central Asia,Europe and Northern America,Europe and Central Asia,Europe,Northern Europe,1.12e-04,0.00e+00,0.00e+00,"POLYGON ((-35.50003 83.49997, -35.50003 83.557...",2.85e-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12209,66602,1.43e-04,2.32e+09,3.32e+05,NZL,New Zealand,0.00e+00,7.53e-05,East Asia and Pacific,Oceania,East Asia and Pacific,Oceania,Australia and New Zealand,2.53e-04,0.00e+00,0.00e+00,"MULTIPOLYGON (((168.49997 -46.59490, 168.50013...",5.53e-01
12210,66603,5.22e-05,3.55e+08,1.85e+04,NZL,New Zealand,0.00e+00,7.53e-05,East Asia and Pacific,Oceania,East Asia and Pacific,Oceania,Australia and New Zealand,2.53e-04,0.00e+00,0.00e+00,"POLYGON ((168.99997 -46.50003, 169.49997 -46.5...",6.55e-02
12211,66604,2.49e-05,5.95e+07,1.48e+03,NZL,New Zealand,0.00e+00,7.53e-05,East Asia and Pacific,Oceania,East Asia and Pacific,Oceania,Australia and New Zealand,2.53e-04,0.00e+00,0.00e+00,"POLYGON ((169.49997 -46.50003, 169.71089 -46.5...",9.79e-03
12212,66623,3.22e-06,3.11e+08,1.00e+03,NZL,New Zealand,0.00e+00,7.53e-05,East Asia and Pacific,Oceania,East Asia and Pacific,Oceania,Australia and New Zealand,2.53e-04,0.00e+00,0.00e+00,"MULTIPOLYGON (((167.49997 -47.19830, 167.50006...",7.93e-02
12213,66624,4.21e-05,7.54e+07,3.18e+03,NZL,New Zealand,0.00e+00,7.53e-05,East Asia and Pacific,Oceania,East Asia and Pacific,Oceania,Australia and New Zealand,2.53e-04,0.00e+00,0.00e+00,"MULTIPOLYGON (((167.99997 -47.00003, 168.21190...",2.18e-02

In [4]:
#import data on water consumption
water_consumption=pd.read_excel(path_directory+'/data/WaterConsumption_2019_notextrapolated_toSend.xlsx', sheet_name="actual_consumption_allsectors")
water_consumption

,Basin_ID,BasinCons_InclNegat_Jan_m3,BasinCons_InclNegat_Feb_m3,BasinCons_InclNegat_Mar_m3,BasinCons_InclNegat_Apr_m3,BasinCons_InclNegat_May_m3,BasinCons_InclNegat_Jun_m3,BasinCons_InclNegat_Jul_m3,BasinCons_InclNegat_Aug_m3,BasinCons_InclNegat_Sep_m3,...,BasinCons_May_m3,BasinCons_Jun_m3,BasinCons_Jul_m3,BasinCons_Aug_m3,BasinCons_Sep_m3,BasinCons_Oct_m3,BasinCons_Nov_m3,BasinCons_Dec_m3,Total_cons_m3,CellCount
0,2,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,...,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1
1,3,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,...,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1
2,4,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,...,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1
3,5,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,...,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1
4,6,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,...,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11656,78504,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,...,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1
11657,78505,1.89e+00,1.71e+00,1.89e+00,1.83e+00,1.89e+00,1.83e+00,1.89e+00,1.89e+00,1.83e+00,...,1.89e+00,1.83e+00,1.89e+00,1.89e+00,1.83e+00,1.89e+00,1.83e+00,1.89e+00,2.23e+01,1
11658,78519,1.35e+02,1.22e+02,1.35e+02,1.31e+02,1.35e+02,1.31e+02,1.35e+02,1.35e+02,1.31e+02,...,1.35e+02,1.31e+02,1.35e+02,1.35e+02,1.31e+02,1.35e+02,1.31e+02,1.35e+02,1.59e+03,1
11659,78526,6.64e+00,5.99e+00,6.64e+00,6.42e+00,6.64e+00,6.42e+00,6.64e+00,6.64e+00,6.42e+00,...,6.64e+00,6.42e+00,6.64e+00,6.64e+00,6.42e+00,6.64e+00,6.42e+00,6.64e+00,7.81e+01,1
11660,78541,1.27e+03,1.15e+03,1.27e+03,1.23e+03,1.27e+03,4.15e+03,1.27e+03,1.27e+03,1.23e+03,...,1.27e+03,4.15e+03,1.27e+03,1.27e+03,1.23e+03,1.27e+03,1.23e+03,1.27e+03,1.79e+04,1

While CF at the subriver basin level are available, current LCI databases limit their use due to coarse regionalisation of water inventory flows. In ecoinvent, different geographies of inventory flows are developed (countries, 'aluminium', 'legacy', 'states', 'electricity','un-subregions', 'special', 'russia', 'un-regions','usa-electricity'). To be operationalized, CF must be aggregated by (ecoinvent) regions. Regional-scaled CF are calculated by aggregating CF by water use ;  Regional-scaled CF are calculated as the weighted sum of CF (subriver basin) multiplied by the percentage of water use in the subriver basin compared to water use in the region. 

Water use data is provided by the WaterGAP model at the subriver basin level. Boundaries of subriver basins do not match with those of ecoinvent regions. 
To calculate regions-scaled CF, shapefiles of water use and subriver basin CF are intersected, leading to smaller "sub-sub river basins". Water use in sub-sub-river basins is estimated based on water use in the sub-river basin, and on the surface of the sub subriver basin compared to original subriver basin (Water use in subsubriver basin = area subsubriver basin/area subriver basin * water use subriver basin). We assume here that water use is proportional to surface. 

Then, regional-scaled CF are calculated as Sum(CF sub-subriver* %Water use in subsubriver basin).

In [5]:
# Calculate the percentage_area of each subiver basin (compared to riverbasin)

# Calculate the sum of cell_area for each BAS34S_ID
CF['sum_cell_area'] = CF.groupby('BAS34S_ID')['cell_area'].transform('sum')

# Calculate the percentage_area
CF['percentage_area'] = CF['cell_area'] / CF['sum_cell_area']

In [6]:
#merge CF geodataframe and water use dataframe to quantify water usage per subriver basin
CF_aggregated=pd.merge(CF,water_consumption.rename(columns={"Basin_ID":"BAS34S_ID"})[["BAS34S_ID","Total_cons_m3"]], on="BAS34S_ID", how='left' )

#recalculate water usage per subriver basin (to consider countries) 
CF_aggregated["Conso_subriv_m3"]=CF_aggregated["percentage_area"]*CF_aggregated["Total_cons_m3"]

#Calculate water consumption per region 
CF_aggregated["Conso_country_GLAM_m3"]=CF_aggregated.groupby('ROMNAM')['Conso_subriv_m3'].transform('sum')   #ROMNAM is the name of the country name in the geography provided by GLAM
CF_aggregated["Conso_Region_WorldBank_m3"]=CF_aggregated.groupby('Region (Wo')['Conso_subriv_m3'].transform('sum')
CF_aggregated["Conso_Region_UN_m3"]=CF_aggregated.groupby('Region (Un')['Conso_subriv_m3'].transform('sum')
CF_aggregated["Conso_Region_WorldBank/UN_m3"]=CF_aggregated.groupby('Region (WB')['Conso_subriv_m3'].transform('sum')
CF_aggregated["Conso_global_m3"]=CF_aggregated['Conso_subriv_m3'].sum()

# Calculate the product of CF and the percentage of conso in the region m3 
CF_aggregated['CF_country_GLAM'] = CF_aggregated['CF'] * CF_aggregated["Conso_subriv_m3"]/CF_aggregated["Conso_country_GLAM_m3"]
CF_aggregated['CF_Region_WorldBank'] = CF_aggregated['CF'] * CF_aggregated["Conso_subriv_m3"]/CF_aggregated["Conso_Region_WorldBank_m3"]
CF_aggregated['CF_Region_UN'] = CF_aggregated['CF'] * CF_aggregated["Conso_subriv_m3"]/CF_aggregated["Conso_Region_UN_m3"]
CF_aggregated['CF_Region_WorldBank/UN'] = CF_aggregated['CF'] * CF_aggregated["Conso_subriv_m3"]/CF_aggregated["Conso_Region_WorldBank/UN_m3"]
CF_aggregated['CF_global'] = CF_aggregated['CF'] * CF_aggregated["Conso_subriv_m3"]/CF_aggregated["Conso_global_m3"]

#suming the results per region
CF_aggregated['CF_country_GLAM'] = CF_aggregated.groupby("ISO3CD")['CF_country_GLAM'].transform('sum')
CF_aggregated['CF_Region_WorldBank'] = CF_aggregated.groupby("Region (Wo")['CF_Region_WorldBank'].transform('sum')
CF_aggregated['CF_Region_UN'] = CF_aggregated.groupby("Region (Un")['CF_Region_UN'].transform('sum')
CF_aggregated['CF_Region_WorldBank/UN'] = CF_aggregated.groupby("Region (WB")['CF_Region_UN'].transform('sum')
CF_aggregated['CF_global']=CF_aggregated['CF_global'].sum()

CF_aggregated

,BAS34S_ID,Scarcity,TOTAL_avai,dom,ISO3CD,ROMNAM,XF,EF,Region (Wo,Region (Un,...,Conso_country_GLAM_m3,Conso_Region_WorldBank_m3,Conso_Region_UN_m3,Conso_Region_WorldBank/UN_m3,Conso_global_m3,CF_country_GLAM,CF_Region_WorldBank,CF_Region_UN,CF_Region_WorldBank/UN,CF_global
0,2,0.00e+00,7.68e+06,0.00e+00,DNK,Denmark,0.00e+00,8.41e-05,Europe and Central Asia,Europe and Northern America,...,3.18e+08,1.88e+11,2.18e+11,1.88e+11,1.38e+12,0.00e+00,3.26e-06,2.55e-08,2.36e-02,1.95e-05
1,4,0.00e+00,1.49e+07,0.00e+00,DNK,Denmark,0.00e+00,8.41e-05,Europe and Central Asia,Europe and Northern America,...,3.18e+08,1.88e+11,2.18e+11,1.88e+11,1.38e+12,0.00e+00,3.26e-06,2.55e-08,2.36e-02,1.95e-05
2,5,0.00e+00,1.60e+07,0.00e+00,DNK,Denmark,0.00e+00,8.41e-05,Europe and Central Asia,Europe and Northern America,...,3.18e+08,1.88e+11,2.18e+11,1.88e+11,1.38e+12,0.00e+00,3.26e-06,2.55e-08,2.36e-02,1.95e-05
3,6,0.00e+00,1.63e+07,0.00e+00,DNK,Denmark,0.00e+00,8.41e-05,Europe and Central Asia,Europe and Northern America,...,3.18e+08,1.88e+11,2.18e+11,1.88e+11,1.38e+12,0.00e+00,3.26e-06,2.55e-08,2.36e-02,1.95e-05
4,7,0.00e+00,1.59e+07,0.00e+00,DNK,Denmark,0.00e+00,8.41e-05,Europe and Central Asia,Europe and Northern America,...,3.18e+08,1.88e+11,2.18e+11,1.88e+11,1.38e+12,0.00e+00,3.26e-06,2.55e-08,2.36e-02,1.95e-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12209,66602,1.43e-04,2.32e+09,3.32e+05,NZL,New Zealand,0.00e+00,7.53e-05,East Asia and Pacific,Oceania,...,1.66e+09,4.08e+11,2.22e+10,4.08e+11,1.38e+12,0.00e+00,3.63e-07,5.69e-11,6.75e-04,1.95e-05
12210,66603,5.22e-05,3.55e+08,1.85e+04,NZL,New Zealand,0.00e+00,7.53e-05,East Asia and Pacific,Oceania,...,1.66e+09,4.08e+11,2.22e+10,4.08e+11,1.38e+12,0.00e+00,3.63e-07,5.69e-11,6.75e-04,1.95e-05
12211,66604,2.49e-05,5.95e+07,1.48e+03,NZL,New Zealand,0.00e+00,7.53e-05,East Asia and Pacific,Oceania,...,1.66e+09,4.08e+11,2.22e+10,4.08e+11,1.38e+12,0.00e+00,3.63e-07,5.69e-11,6.75e-04,1.95e-05
12212,66623,3.22e-06,3.11e+08,1.00e+03,NZL,New Zealand,0.00e+00,7.53e-05,East Asia and Pacific,Oceania,...,1.66e+09,4.08e+11,2.22e+10,4.08e+11,1.38e+12,0.00e+00,3.63e-07,5.69e-11,6.75e-04,1.95e-05
12213,66624,4.21e-05,7.54e+07,3.18e+03,NZL,New Zealand,0.00e+00,7.53e-05,East Asia and Pacific,Oceania,...,1.66e+09,4.08e+11,2.22e+10,4.08e+11,1.38e+12,0.00e+00,3.63e-07,5.69e-11,6.75e-04,1.95e-05

In [7]:
#CF_aggregated.to_csv(path_directory+"/results/CF/CF_aggregated_per_country_GLAM_and_classifications.csv")

# ecoinvent regions

In [8]:
#import shapefile for ecoinvent geometries
ecoinvent_regions=gpd.read_file(path_directory+'/data/all.gpkg') #all geographies from the ecoinvent dataset - updated on 06/03/2024
ecoinvent_regions=ecoinvent_regions[["id","gid","collection","name","isothreelettercode","unsubregion","unregion","shortname","geometry"]]
ecoinvent_regions

,id,gid,collection,name,isothreelettercode,unsubregion,unregion,shortname,geometry
0,2,2.58e+02,countries,Scarborough Reef,None,South-Eastern Asia,Asia,Scarborough Reef,"MULTIPOLYGON (((117.75389 15.15437, 117.75569 ..."
1,56,5.00e+01,countries,Germany,DEU,Western Europe,Europe,DE,"MULTIPOLYGON (((7.33400 49.13416, 7.32646 49.1..."
2,57,5.10e+01,countries,Estonia,EST,Northern Europe,Europe,EE,"MULTIPOLYGON (((23.25025 57.78437, 23.22950 57..."
3,148,1.43e+02,countries,Turkmenistan,TKM,Central Asia,Asia,TM,"MULTIPOLYGON (((62.73424 35.28074, 62.72163 35..."
4,79,7.30e+01,countries,Tunisia,TUN,Northern Africa,Africa,TN,"MULTIPOLYGON (((10.77286 32.00451, 10.73658 31..."
...,...,...,...,...,...,...,...,...,...
535,3,1.69e+02,countries,Northern Cyprus,None,Western Asia,Asia,Northern Cyprus,"MULTIPOLYGON (((32.61940 35.18488, 32.64069 35..."
536,174,1.71e+02,countries,Siachen Glacier,None,Southern Asia,Asia,Siachen Glacier,"MULTIPOLYGON (((77.04897 35.11044, 76.91316 35..."
537,249,2.51e+02,countries,Coral Sea Islands,None,Australia and New Zealand,Oceania,Coral Sea Islands,"MULTIPOLYGON (((153.48772 -21.84914, 153.48764..."
538,27,2.10e+01,countries,Somaliland,None,Eastern Africa,Africa,Somaliland,"MULTIPOLYGON (((43.18881 11.40776, 43.24073 11..."
539,265,1.00e+05,countries,Crimea,None,Eastern Europe,Europe,Crimea,"MULTIPOLYGON (((33.72096 44.39964, 33.64536 44..."

In [9]:
ecoinvent_regions.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

ecoinvent has different geographies : 'countries', 'aluminium', 'legacy', 'states', 'electricity','un-subregions', 'special', 'russia', 'un-regions','usa-electricity

In [10]:
#list of ecoinvent geometries
geographies=['countries','aluminium', 'legacy', 'states', 'electricity',
       'un-subregions', 'special', 'russia', 'un-regions',
       'usa-electricity']

#create a dictionary containing the dataframes with CF aggregated per ecoinvent geographies (10 df)
dict_df_geographies = {}  # Create an empty dictionary to store DataFrames

#for each geography, we proceed to the intersection between the CF (subriver) and the geography
for geo in geographies:
    dict_df_geographies[geo] = ecoinvent_regions[ecoinvent_regions['collection'] == geo].rename(columns={"isothreelettercode": "ISO3CD"})  #we select the geography we want
    dict_df_geographies[geo] = gpd.overlay(CF_aggregated, dict_df_geographies[geo], how="intersection",keep_geom_type=False) #proceed to the intersection

In [11]:
#for each geography, we proceed to the calculation of the % of water consumption of the cell compared to the geographyfor geo in geographies followed by the weighted CF in the cell:

dict_CF=dict_df_geographies

for geo in geographies:
    dict_CF[geo]=dict_CF[geo][['BAS34S_ID', 'Scarcity','XF','EF', 'CF', 'ISO3CD_1', 'ROMNAM','CF_country_GLAM', 'Total_cons_m3','id', 'gid', 'collection', 'name', 'ISO3CD_2','unsubregion', 'unregion', 'shortname','geometry']]
    dict_CF[geo]["cell_area"]=dict_CF[geo].area
   
    # Calculate the sum of cell_area for each BAS34S_ID
    dict_CF[geo]['sum_cell_area'] = dict_CF[geo].groupby('BAS34S_ID')['cell_area'].transform('sum')

    # Calculate the percentage_area
    dict_CF[geo]['percentage_area'] = dict_CF[geo]['cell_area'] / dict_CF[geo]['sum_cell_area']

    #recalculate water usage per subriver basin (to consider countries) 
    dict_CF[geo]["Conso_cell_m3"]=dict_CF[geo]["percentage_area"]*dict_CF[geo]["Total_cons_m3"]

<ipython-input-11-969c2ee2f37b>:7: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  dict_CF[geo]["cell_area"]=dict_CF[geo].area
<ipython-input-11-969c2ee2f37b>:7: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  dict_CF[geo]["cell_area"]=dict_CF[geo].area
<ipython-input-11-969c2ee2f37b>:7: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  dict_CF[geo]["cell_area"]=dict_CF[geo].area
<ipython-input-11-969c2ee2f37b>:7: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  dict_CF[geo]["cell_area"]=dict_CF[geo].area
<ipython-input-11-969c2ee2f37b>:7: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  dict_CF[geo]["cell_area"]=dict_CF[geo].area
<ipython-input-11-969c2ee2f37b>:7: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  dict_CF[geo]["cell_area"]=dict_CF[geo].area
<ipython-input-11-969c2ee2f37b>:7: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  dict_CF[geo]["cell_area"]=dict_CF[geo].area
<ipython-input-11-969c2ee2f37b>:7: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  dict_CF[geo]["cell_area"]=dict_CF[geo].area
<ipython-input-11-969c2ee2f37b>:7: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  dict_CF[geo]["cell_area"]=dict_CF[geo].area
<ipython-input-11-969c2ee2f37b>:7: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  dict_CF[geo]["cell_area"]=dict_CF[geo].area

In [15]:
#for each geometry, we 1- recalculate the total consumption, 2- Compute CF and percentage of conso in the region

CF_per_geom={}

for geo in geographies:
    dict_CF[geo]["conso_"+geo]=dict_CF[geo].groupby('name')["Conso_cell_m3"].transform('sum')
    dict_CF[geo]["CF_"+geo]=dict_CF[geo]["CF"]*dict_CF[geo]["Conso_cell_m3"]/dict_CF[geo]["conso_"+geo]
    dict_CF[geo]["CF_"+geo]=dict_CF[geo].groupby('name')["CF_"+geo].transform('sum')
 
for geo in ['aluminium', 'legacy', 'states', 'electricity',
       'un-subregions', 'special', 'russia', 'un-regions',
       'usa-electricity']:
    CF_per_geom[geo]=dict_CF[geo][['collection', 'name', 'shortname', 
       'CF_'+geo]]

CF_per_geom["countries"]=dict_CF["countries"][['ISO3CD_1','ROMNAM','CF_country_GLAM','collection', 'name', 'ISO3CD_2',
       'unsubregion', 'unregion', 'shortname', 
       'CF_countries', 'geometry']]
CF_per_geom["countries"]=CF_per_geom["countries"].rename(columns={"ISO3CD_1":"ISO3_GLAM", "ISO3CD_2":"ISO3_ecoinvent"})

In [18]:
CF_countries=CF_per_geom["countries"]

In [16]:
# Comparison of country geographies : GLAM and ecoinvent
CF_countries=CF_per_geom["countries"]
CF_countries

list_ISO3_GLAM=CF_countries[["ISO3_GLAM", "ROMNAM", "CF_country_GLAM","ISO3_ecoinvent","name","CF_countries"]].drop_duplicates(subset="ISO3_GLAM")
list_ISO3_ecoinvent=CF_countries[["ISO3_GLAM", "ROMNAM", "CF_country_GLAM","ISO3_ecoinvent","name","CF_countries"]].drop_duplicates(subset="ISO3_ecoinvent")

list_ISO3_GLAM_only=CF_countries[["ISO3_GLAM","ROMNAM"]].drop_duplicates(subset="ISO3_GLAM")
list_ISO3_ecoinvent_only=CF_countries[["ISO3_ecoinvent","name"]].drop_duplicates(subset="ISO3_ecoinvent")


list_ISO3_GLAM_only #188 rows
list_ISO3_ecoinvent_only #221 rows


# Convert the columns to sets
set_GLAM = set(list_ISO3_GLAM_only['ISO3_GLAM'])
set_ecoinvent = set(list_ISO3_ecoinvent_only['ISO3_ecoinvent'])

# Find common elements
common_elements = set_GLAM & set_ecoinvent

# Find elements only in df_ISO3_GLAM_only
only_in_GLAM = set_GLAM - set_ecoinvent

# Find elements only in df_ISO3_ecoinvent_only
only_in_ecoinvent = set_ecoinvent - set_GLAM

# Create DataFrames for common and unique elements
df_common = list_ISO3_GLAM_only[list_ISO3_GLAM_only['ISO3_GLAM'].isin(common_elements)]
df_only_in_GLAM = list_ISO3_GLAM_only[list_ISO3_GLAM_only['ISO3_GLAM'].isin(only_in_GLAM)]
df_only_in_ecoinvent = list_ISO3_ecoinvent_only[list_ISO3_ecoinvent_only['ISO3_ecoinvent'].isin(only_in_ecoinvent)]

# CREATING FILES STORING CFs

FOR COUNTRIES

In [17]:
CF_countries

,ISO3_GLAM,ROMNAM,CF_country_GLAM,collection,name,ISO3_ecoinvent,unsubregion,unregion,shortname,CF_countries,geometry
0,DNK,Denmark,0.00e+00,countries,Greenland,GRL,Northern America,Americas,GL,0.00e+00,"POLYGON ((-37.57730 83.49997, -37.87779 83.499..."
1,DNK,Denmark,0.00e+00,countries,Greenland,GRL,Northern America,Americas,GL,0.00e+00,"POLYGON ((-36.50003 83.49997, -36.76440 83.499..."
2,DNK,Denmark,0.00e+00,countries,Greenland,GRL,Northern America,Americas,GL,0.00e+00,"POLYGON ((-36.50003 83.53789, -36.24026 83.537..."
3,DNK,Denmark,0.00e+00,countries,Greenland,GRL,Northern America,Americas,GL,0.00e+00,"POLYGON ((-36.00003 83.53761, -35.74193 83.537..."
4,DNK,Denmark,0.00e+00,countries,Greenland,GRL,Northern America,Americas,GL,0.00e+00,"POLYGON ((-35.50003 83.53732, -35.24360 83.537..."
...,...,...,...,...,...,...,...,...,...,...,...
14636,NZL,New Zealand,0.00e+00,countries,New Zealand,NZL,Australia and New Zealand,Oceania,NZ,0.00e+00,"MULTIPOLYGON (((168.50013 -46.59499, 168.50025..."
14637,NZL,New Zealand,0.00e+00,countries,New Zealand,NZL,Australia and New Zealand,Oceania,NZ,0.00e+00,"MULTIPOLYGON (((169.49997 -46.50003, 169.49997..."
14638,NZL,New Zealand,0.00e+00,countries,New Zealand,NZL,Australia and New Zealand,Oceania,NZ,0.00e+00,"POLYGON ((169.71089 -46.50003, 169.71098 -46.5..."
14639,NZL,New Zealand,0.00e+00,countries,New Zealand,NZL,Australia and New Zealand,Oceania,NZ,0.00e+00,"MULTIPOLYGON (((167.66515 -47.04028, 167.66526..."
14640,NZL,New Zealand,0.00e+00,countries,New Zealand,NZL,Australia and New Zealand,Oceania,NZ,0.00e+00,"MULTIPOLYGON (((168.21190 -47.00003, 168.21194..."

In [19]:
#COMPLETE THE COMMON LIST (GLAM) WITH CF

# Ensure the columns you are joining on have the same type
df_common['ISO3_GLAM'] = df_common['ISO3_GLAM'].astype(str)
CF_countries['ISO3_GLAM'] = CF_countries['ISO3_GLAM'].astype(str)
# Remove duplicates in CF_countries based on ISO3_GLAM
CF_countries_unique = CF_countries.drop_duplicates(subset='ISO3_GLAM')

common_df=df_common.merge(CF_countries_unique, on="ISO3_GLAM", how="left", suffixes=('_GLAM', '_ecoinvent'))
common_df=common_df.drop(columns=['ROMNAM_ecoinvent','name'])
common_df=common_df.rename(columns={"ROMNAM_GLAM":"ROMNAM"})
common_df

,ISO3_GLAM,ROMNAM,CF_country_GLAM,collection,ISO3_ecoinvent,unsubregion,unregion,shortname,CF_countries,geometry
0,DNK,Denmark,0.00e+00,countries,GRL,Northern America,Americas,GL,0.00e+00,"POLYGON ((-37.57730 83.49997, -37.87779 83.499..."
1,DEU,Germany,0.00e+00,countries,DNK,Northern Europe,Europe,DK,0.00e+00,"MULTIPOLYGON (((9.35410 54.81347, 9.35435 54.8..."
2,POL,Poland,0.00e+00,countries,DEU,Western Europe,Europe,DE,0.00e+00,"POLYGON ((14.19240 53.91204, 14.18529 53.91190..."
3,CZE,Czechia,0.00e+00,countries,DEU,Western Europe,Europe,DE,0.00e+00,"MULTIPOLYGON (((14.49028 51.02250, 14.49250 51..."
4,AUT,Austria,0.00e+00,countries,DEU,Western Europe,Europe,DE,0.00e+00,"MULTIPOLYGON (((9.95753 47.53502, 9.96153 47.5..."
...,...,...,...,...,...,...,...,...,...,...
183,VUT,Vanuatu,0.00e+00,countries,VUT,Melanesia,Oceania,VU,0.00e+00,"MULTIPOLYGON (((167.49155 -13.91040, 167.49089..."
184,FJI,Fiji,4.05e-08,countries,FJI,Melanesia,Oceania,FJ,4.05e-08,"MULTIPOLYGON (((178.99997 -16.46652, 179.00093..."
185,TON,Tonga,0.00e+00,countries,TON,Polynesia,Oceania,TO,0.00e+00,"MULTIPOLYGON (((-174.00000 -18.64528, -173.998..."
186,MUS,Mauritius,2.68e-06,countries,MUS,Eastern Africa,Africa,MU,2.68e-06,"MULTIPOLYGON (((57.39360 -20.50003, 57.39207 -..."
187,NZL,New Zealand,0.00e+00,countries,NZL,Australia and New Zealand,Oceania,NZ,0.00e+00,"MULTIPOLYGON (((172.95046 -34.50003, 172.95045..."

In [20]:
#COMPLETE THE ONLY IN ECOINVENT LIST WITH CF

df_only_in_ecoinvent

# Ensure the columns you are joining on have the same type
df_only_in_ecoinvent['ISO3_ecoinvent'] = df_only_in_ecoinvent['ISO3_ecoinvent'].astype(str)
CF_countries['ISO3_ecoinvent'] = CF_countries['ISO3_ecoinvent'].astype(str)

# Remove duplicates in CF_countries based on ISO3_GLAM
CF_countries_unique = CF_countries.drop_duplicates(subset='ISO3_ecoinvent')

only_in_ecoinvent_df=df_only_in_ecoinvent.merge(CF_countries_unique, on="ISO3_ecoinvent", how="left")
only_in_ecoinvent_df=only_in_ecoinvent_df.drop(columns=['name_y'])
only_in_ecoinvent_df=only_in_ecoinvent_df.rename(columns={"name_x":"name_ecoinvent"})
only_in_ecoinvent_df

<ipython-input-20-3c81fd1fde30>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_only_in_ecoinvent['ISO3_ecoinvent'] = df_only_in_ecoinvent['ISO3_ecoinvent'].astype(str)

,ISO3_ecoinvent,name_ecoinvent,ISO3_GLAM,ROMNAM,CF_country_GLAM,collection,unsubregion,unregion,shortname,CF_countries,geometry
0,GRL,Greenland,DNK,Denmark,0.00e+00,countries,Northern America,Americas,GL,0.00e+00,"POLYGON ((-37.57730 83.49997, -37.87779 83.499..."
1,FRO,Faroe Islands,DNK,Denmark,0.00e+00,countries,Northern Europe,Europe,FO,0.00e+00,"MULTIPOLYGON (((-7.07357 62.31538, -7.06475 62..."
2,SJM,Svalbard and Jan Mayen,NOR,Norway,0.00e+00,countries,Northern Europe,Europe,SJ,0.00e+00,"MULTIPOLYGON (((10.99997 79.55613, 11.04211 79..."
3,PRI,Puerto Rico,USA,United States of America,0.00e+00,countries,Caribbean,Americas,PR,0.00e+00,"POLYGON ((-67.84807 18.10662, -67.84558 18.101..."
4,VIR,United States Virgin Islands,USA,United States of America,0.00e+00,countries,Caribbean,Americas,VI,0.00e+00,"POLYGON ((-65.00064 18.34661, -65.00136 18.346..."
...,...,...,...,...,...,...,...,...,...,...,...
28,GUF,French Guiana,FRA,France,0.00e+00,countries,South America,Americas,GF,1.26e-12,"POLYGON ((-53.50003 3.99997, -53.50003 3.49997..."
29,MYT,Mayotte,FRA,France,0.00e+00,countries,Eastern Africa,Africa,YT,0.00e+00,"MULTIPOLYGON (((45.28412 -12.79607, 45.28105 -..."
30,NCL,New Caledonia,FRA,France,0.00e+00,countries,Melanesia,Oceania,NC,0.00e+00,"MULTIPOLYGON (((164.15736 -20.43112, 164.15039..."
31,REU,Réunion,FRA,France,0.00e+00,countries,Eastern Africa,Africa,RE,0.00e+00,"POLYGON ((55.28099 -20.99378, 55.28409 -20.986..."
32,-99,Kosovo,ALB,Albania,2.54e-07,countries,Southern Europe,Europe,XK,1.54e-07,"MULTIPOLYGON (((20.31393 42.32040, 20.31549 42..."

In [21]:
df_common_renamed = common_df.rename(columns={'ROMNAM': 'name', "ISO3_GLAM":"ISO3"})
df_common_renamed['geography origin'] = 'GLAM'
# Rename columns in df_only_in_ecoinvent
df_only_in_ecoinvent_renamed = only_in_ecoinvent_df.rename(columns={'name_ecoinvent': 'name', 'ROMNAM':"name in GLAM geography", "ISO3_ecoinvent":"ISO3"})
df_only_in_ecoinvent_renamed['geography origin'] = 'ecoinvent'
# Combine the DataFrames
df_combined = pd.concat([df_common_renamed, df_only_in_ecoinvent_renamed], ignore_index=True).rename(columns={'CF_countries': 'CF_with_agg_ecoinvent'})

# Filter rows where 'geography origin' is not 'GLAM' and set values in 'ISO3_ecoinvent' and 'unsubregion' columns to None
df_combined.loc[df_combined['geography origin'] == 'GLAM', ['ISO3_ecoinvent', 'unsubregion','unregion','shortname']] = None

desired_columns = ['ISO3', 'name', 'geography origin', 'CF_country_GLAM',
                   'ISO3_GLAM', 'name in GLAM geography', 'collection']


df_combined.reindex(columns=desired_columns)

#SAVE CFs per country as a csv file
df_combined.reindex(columns=desired_columns).to_csv(path_directory+'/results/CF/Aggregated_ecoinvent_regions/CF_per_country.csv')

FOR OTHER GEOGRAPHIES

In [22]:
CF_short_per_geom={}

Ecoinvent_regions=ecoinvent_regions[["name","geometry"]]
Ecoinvent_regions['name'] = Ecoinvent_regions['name'].astype(str)

for geo in ['aluminium', 'legacy', 'states', 'electricity',
       'un-subregions', 'special', 'russia', 'un-regions',
       'usa-electricity']:
    CF_short_per_geom[geo]=CF_per_geom[geo].drop_duplicates(subset="name")
    CF_short_per_geom[geo]=CF_short_per_geom[geo].set_index('name').join(Ecoinvent_regions.set_index('name'), how='left')
    

    #Save to csv
    CF_short_per_geom[geo].to_csv(path_directory+'/results/CF/Aggregated_ecoinvent_regions/CF_per_ecoinvent_geom_'+geo+'.csv')

/opt/anaconda3/lib/python3.8/site-packages/geopandas/geodataframe.py:1351: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [23]:
type(CF_short_per_geom['aluminium'])

pandas.core.frame.DataFrame

# Sanity check - Normalisation

In [25]:
CF_subriv=CF_aggregated

#Calculate total impact for year 2019 withh subriver scale CF
CF_subriv['Imp_subriv']=CF_subriv["Conso_subriv_m3"]*CF_subriv["CF"]
CF_subriv['Imp_country']=CF_subriv["Conso_subriv_m3"]*CF_subriv["CF_country_GLAM"]
CF_subriv['Imp_global']=CF_subriv["Conso_subriv_m3"]*CF_subriv["CF_global"]

print('global impact at subriver scale (using subriverbasin values) is ' + str(CF_subriv["Imp_subriv"].sum()) + ' DALYs' + '\n' + 
      'global impact at country scale (using subriverbasin values) is ' + str(CF_subriv["Imp_country"].sum()) + ' DALYs' + '\n' +
      'global impact at global scale (using subriverbasin values) is ' + str(CF_subriv["Imp_global"].sum()) + ' DALYs' + '\n')

global impact at subriver scale (using subriverbasin values) is 27037517.495576214 DALYs
global impact at country scale (using subriverbasin values) is 27037962.055613536 DALYs
global impact at global scale (using subriverbasin values) is 27037517.495576207 DALYs

In [26]:
CF_global=0.0000195607105580389
total_water_consumption=CF_subriv["Conso_subriv_m3"].sum()
total_water_consumption

#Normalized impact (DALY) - global scale
result = CF_global*total_water_consumption

# Using the format method
formatted_result = "{:e}".format(result)
print("Global normalized impact =", formatted_result)

Global normalized impact = 2.707217e+07

In [ ]:
total_water_consumption

In [ ]:
Impact_country=CF_aggregated[["ISO3CD","Conso_country_GLAM_m3","CF_country_GLAM"]].drop_duplicates(subset='ISO3CD')
Impact_country["Impact_country"]=Impact_country["Conso_country_GLAM_m3"]*Impact_country["CF_country_GLAM"]
Impact_country

In [ ]:
Impact_country.sum()